name: Aws Services CI
env:
  SERVICES: dynamodb,sqs,s3 # Add more services depending on your test case
  NODE_ENV: test
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:14.5.0-alpine
    services:
      localstack:
        image: localstack/localstack
        ports:
          - "4566-4599:4566-4599"
          - 8080:8080
        env:
          - SERVICES: ${{ env.MYSQL_DATABASE }}
          - DEBUG: ${DEBUG- }
          - DATA_DIR: ${DATA_DIR- }
          - LAMBDA_EXECUTOR: ${LAMBDA_EXECUTOR- }
          - KINESIS_ERROR_PROBABILITY: ${KINESIS_ERROR_PROBABILITY- }
          - DOCKER_HOST: unix:///var/run/docker.sock
          - HOST_TMP_FOLDER: ${TMPDIR}
        options: >-
          --name=localstack
          --health-cmd="ping localhost:8080"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: "npm ci"
      # - name: Run Tests
      #   run: "npm run test"
